version: '3.6'

services:
  db:
    image: postgres
    build:
      context: .
      dockerfile: ./postgres.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    expose:
      - 54325
    ports:
      - 127.0.0.1:54325:5432

